spring:
  main:
    log-startup-info: false
    banner-mode: off
  datasource:
    url: jdbc:sqlite:/home/amrod/develop/ninja-bot/src/main/resources/dnd.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
logging:
  level:
    root: off
    org.pubcoding: info
  pattern:
    console: "%msg%n"