spring:
  main:
    log-startup-info: false
    banner-mode: off
  datasource:
    url: jdbc:sqlite:/Users/marcoriggio/develop/ninjabot/src/main/resources/dnd.db?cache=shared
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.dialect.SQLiteDialect