name: Deploy NinjaBot

on:
  push:
    branches: [ "main" ]

jobs:
  aws_cdk:
    name: 'CDK build and deployment'
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Assume Role
        uses: youyo/awscredswrap@master
        with:
          role_arn: ${{ secrets.ROLE_ARN }}
          duration_seconds: 3600
          role_session_name: 'awscredswrap@GitHubActions'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      - uses: actions/checkout@v4
      - name: Deploy
        uses: youyo/aws-cdk-github-actions@v2
        with:
          working_dir: 'ninja_bot'
          cdk_subcommand: 'deploy --require-approval never'
