name: Native MacOS

on:
  push:
    branches:
      - master

jobs:
  native-image:
    uses: MarcoAlessandroRiggio/ninja-bot/.github/workflows/native.yml@master
    with:
      os: macos-latest
      target_name: ninjacli-macos
      target_path: target/ninjacli
      