name: "Produce Native Image"

on:
  workflow_call:
    inputs:
      os:
        required: true
        description: "OS to use for the build"
        type: string
      target_name:
        required: true
        description: "Target name to produce"
        type: string
      target_path:
        required: true
        description: "Path where find the artifact"
        type: string

jobs:
  package:
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          distribution: 'graalvm'
      - name: Cache the Maven packages to speed up build
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build artifact
        run: mvn --batch-mode --update-snapshots -Pnative package
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ inputs.target_name }}
          path: ${{ inputs.target_path }}

