name: Native Linux

on:
  push:
    branches:
      - master

jobs:
  native-image:
    uses: MarcoAlessandroRiggio/ninja-bot/.github/workflows/native.yml@master
    with:
      os: ubuntu-latest
      target_name: ninjacli-linux
      target_path: target/ninjacli